# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e6c9169002bf972bde65daef6764673ff371d2c568fa0906e4964348d6f138cc826ca640df7595a668b06a76972eec090ea1fc28cf36132dd9395a3864a8d9d

test:
  secret_key_base: fe297acc5492e7c5954302648829fe5d4a2994b15a1d8d9f07f7eff0595b1827c18cad2f6707765ff2537cab76958b214c8f9a5761521d205028dc5712a16148

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
